In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
data = np.random.rand(6,5)
data

array([[0.72113163, 0.49664075, 0.65599143, 0.94341968, 0.30912681],
       [0.06706812, 0.71915421, 0.60898636, 0.19427482, 0.63919842],
       [0.17957817, 0.76668228, 0.48892808, 0.46394653, 0.64058771],
       [0.34501875, 0.52145508, 0.19076961, 0.0266968 , 0.1581963 ],
       [0.90037924, 0.81544085, 0.79547613, 0.0393458 , 0.52782683],
       [0.62528299, 0.15395541, 0.82197729, 0.67157116, 0.1557703 ]])

In [4]:
df = pd.DataFrame(data = data)
df

          0         1         2         3         4
0  0.721132  0.496641  0.655991  0.943420  0.309127
1  0.067068  0.719154  0.608986  0.194275  0.639198
2  0.179578  0.766682  0.488928  0.463947  0.640588
3  0.345019  0.521455  0.190770  0.026697  0.158196
4  0.900379  0.815441  0.795476  0.039346  0.527827
5  0.625283  0.153955  0.821977  0.671571  0.155770

In [5]:
df[0]

0    0.721132
1    0.067068
2    0.179578
3    0.345019
4    0.900379
5    0.625283
Name: 0, dtype: float64

In [6]:
type(df[0])

pandas.core.series.Series

In [7]:
type(df[1])

pandas.core.series.Series

In [10]:
df2 = pd.DataFrame(
    data=data,
    index=['row1', 'row2', 'row3', 'row4', 'row5', 'row6'],
    columns=['col1', 'col2', 'col3', 'col4', 'col5']
)

df2

          col1      col2      col3      col4      col5
row1  0.721132  0.496641  0.655991  0.943420  0.309127
row2  0.067068  0.719154  0.608986  0.194275  0.639198
row3  0.179578  0.766682  0.488928  0.463947  0.640588
row4  0.345019  0.521455  0.190770  0.026697  0.158196
row5  0.900379  0.815441  0.795476  0.039346  0.527827
row6  0.625283  0.153955  0.821977  0.671571  0.155770

---
- coustom colum
---

In [13]:
df2[['col1', 'col2', 'col3']]

          col1      col2      col3
row1  0.721132  0.496641  0.655991
row2  0.067068  0.719154  0.608986
row3  0.179578  0.766682  0.488928
row4  0.345019  0.521455  0.190770
row5  0.900379  0.815441  0.795476
row6  0.625283  0.153955  0.821977

In [15]:
# add new column
df2['new'] = np.random.rand(6)
df2

          col1      col2      col3      col4      col5       new
row1  0.721132  0.496641  0.655991  0.943420  0.309127  0.576612
row2  0.067068  0.719154  0.608986  0.194275  0.639198  0.868929
row3  0.179578  0.766682  0.488928  0.463947  0.640588  0.457065
row4  0.345019  0.521455  0.190770  0.026697  0.158196  0.730163
row5  0.900379  0.815441  0.795476  0.039346  0.527827  0.257036
row6  0.625283  0.153955  0.821977  0.671571  0.155770  0.924124