In [24]:
import numpy as np

In [25]:
import pandas as pd

In [26]:
data = np.random.rand(6,5)
data

array([[0.38706135, 0.17936579, 0.5388689 , 0.87501762, 0.39063594],
       [0.53893152, 0.84168051, 0.94098335, 0.34150989, 0.54668236],
       [0.44491244, 0.07552398, 0.17946293, 0.4168601 , 0.07142088],
       [0.93550856, 0.58986478, 0.71761304, 0.52003638, 0.78930333],
       [0.20806126, 0.67423189, 0.61327624, 0.67406992, 0.04900387],
       [0.18630461, 0.56461905, 0.76873066, 0.62979517, 0.19856308]])

In [27]:
df = pd.DataFrame(data = data)
df

          0         1         2         3         4
0  0.387061  0.179366  0.538869  0.875018  0.390636
1  0.538932  0.841681  0.940983  0.341510  0.546682
2  0.444912  0.075524  0.179463  0.416860  0.071421
3  0.935509  0.589865  0.717613  0.520036  0.789303
4  0.208061  0.674232  0.613276  0.674070  0.049004
5  0.186305  0.564619  0.768731  0.629795  0.198563

In [28]:
df[0]

0    0.387061
1    0.538932
2    0.444912
3    0.935509
4    0.208061
5    0.186305
Name: 0, dtype: float64

In [29]:
type(df[0])

pandas.core.series.Series

In [30]:
type(df[1])

pandas.core.series.Series

In [31]:
df2 = pd.DataFrame(
    data=data,
    index=['row1', 'row2', 'row3', 'row4', 'row5', 'row6'],
    columns=['col1', 'col2', 'col3', 'col4', 'col5']
)

df2

          col1      col2      col3      col4      col5
row1  0.387061  0.179366  0.538869  0.875018  0.390636
row2  0.538932  0.841681  0.940983  0.341510  0.546682
row3  0.444912  0.075524  0.179463  0.416860  0.071421
row4  0.935509  0.589865  0.717613  0.520036  0.789303
row5  0.208061  0.674232  0.613276  0.674070  0.049004
row6  0.186305  0.564619  0.768731  0.629795  0.198563

---
- coustom colum
---

In [32]:
df2[['col1', 'col2', 'col3']]

          col1      col2      col3
row1  0.387061  0.179366  0.538869
row2  0.538932  0.841681  0.940983
row3  0.444912  0.075524  0.179463
row4  0.935509  0.589865  0.717613
row5  0.208061  0.674232  0.613276
row6  0.186305  0.564619  0.768731

In [33]:
# add new column
df2['new'] = np.random.rand(6)
df2

          col1      col2      col3      col4      col5       new
row1  0.387061  0.179366  0.538869  0.875018  0.390636  0.562797
row2  0.538932  0.841681  0.940983  0.341510  0.546682  0.514168
row3  0.444912  0.075524  0.179463  0.416860  0.071421  0.508868
row4  0.935509  0.589865  0.717613  0.520036  0.789303  0.545347
row5  0.208061  0.674232  0.613276  0.674070  0.049004  0.160832
row6  0.186305  0.564619  0.768731  0.629795  0.198563  0.766396

In [34]:
# remove the col
df2.drop('row1')

          col1      col2      col3      col4      col5       new
row2  0.538932  0.841681  0.940983  0.341510  0.546682  0.514168
row3  0.444912  0.075524  0.179463  0.416860  0.071421  0.508868
row4  0.935509  0.589865  0.717613  0.520036  0.789303  0.545347
row5  0.208061  0.674232  0.613276  0.674070  0.049004  0.160832
row6  0.186305  0.564619  0.768731  0.629795  0.198563  0.766396

In [35]:
df3 = df2.drop(columns='col1')

In [36]:
df3

          col2      col3      col4      col5       new
row1  0.179366  0.538869  0.875018  0.390636  0.562797
row2  0.841681  0.940983  0.341510  0.546682  0.514168
row3  0.075524  0.179463  0.416860  0.071421  0.508868
row4  0.589865  0.717613  0.520036  0.789303  0.545347
row5  0.674232  0.613276  0.674070  0.049004  0.160832
row6  0.564619  0.768731  0.629795  0.198563  0.766396

In [37]:
df2

          col1      col2      col3      col4      col5       new
row1  0.387061  0.179366  0.538869  0.875018  0.390636  0.562797
row2  0.538932  0.841681  0.940983  0.341510  0.546682  0.514168
row3  0.444912  0.075524  0.179463  0.416860  0.071421  0.508868
row4  0.935509  0.589865  0.717613  0.520036  0.789303  0.545347
row5  0.208061  0.674232  0.613276  0.674070  0.049004  0.160832
row6  0.186305  0.564619  0.768731  0.629795  0.198563  0.766396

In [38]:
#df2.drop(columns='new', inplace=True)

In [39]:
df2

          col1      col2      col3      col4      col5       new
row1  0.387061  0.179366  0.538869  0.875018  0.390636  0.562797
row2  0.538932  0.841681  0.940983  0.341510  0.546682  0.514168
row3  0.444912  0.075524  0.179463  0.416860  0.071421  0.508868
row4  0.935509  0.589865  0.717613  0.520036  0.789303  0.545347
row5  0.208061  0.674232  0.613276  0.674070  0.049004  0.160832
row6  0.186305  0.564619  0.768731  0.629795  0.198563  0.766396

In [42]:
df2.shape

(6, 6)

In [43]:
df2.drop('new', inplace = False, axis=1)

          col1      col2      col3      col4      col5
row1  0.387061  0.179366  0.538869  0.875018  0.390636
row2  0.538932  0.841681  0.940983  0.341510  0.546682
row3  0.444912  0.075524  0.179463  0.416860  0.071421
row4  0.935509  0.589865  0.717613  0.520036  0.789303
row5  0.208061  0.674232  0.613276  0.674070  0.049004
row6  0.186305  0.564619  0.768731  0.629795  0.198563

In [44]:
df2

          col1      col2      col3      col4      col5       new
row1  0.387061  0.179366  0.538869  0.875018  0.390636  0.562797
row2  0.538932  0.841681  0.940983  0.341510  0.546682  0.514168
row3  0.444912  0.075524  0.179463  0.416860  0.071421  0.508868
row4  0.935509  0.589865  0.717613  0.520036  0.789303  0.545347
row5  0.208061  0.674232  0.613276  0.674070  0.049004  0.160832
row6  0.186305  0.564619  0.768731  0.629795  0.198563  0.766396

In [45]:
df2['col1']

row1    0.387061
row2    0.538932
row3    0.444912
row4    0.935509
row5    0.208061
row6    0.186305
Name: col1, dtype: float64

In [48]:
df2.shape

(6, 6)

In [47]:
# df2['row1']
df2.loc['row1']

col1    0.387061
col2    0.179366
col3    0.538869
col4    0.875018
col5    0.390636
new     0.562797
Name: row1, dtype: float64

In [52]:
df2.loc['row1', 'col2']

0.17936579020237442

In [54]:
df2

          col1      col2      col3      col4      col5       new
row1  0.387061  0.179366  0.538869  0.875018  0.390636  0.562797
row2  0.538932  0.841681  0.940983  0.341510  0.546682  0.514168
row3  0.444912  0.075524  0.179463  0.416860  0.071421  0.508868
row4  0.935509  0.589865  0.717613  0.520036  0.789303  0.545347
row5  0.208061  0.674232  0.613276  0.674070  0.049004  0.160832
row6  0.186305  0.564619  0.768731  0.629795  0.198563  0.766396

In [55]:
df2.loc[['row1', "row2"], ['col3','col4']]

          col3      col4
row1  0.538869  0.875018
row2  0.940983  0.341510

In [57]:
df2.iloc[[0,1], [2,4]]

          col3      col5
row1  0.538869  0.390636
row2  0.940983  0.546682