In [2]:
import numpy as np
import pandas as pd

In [3]:
groups = ['group1']*3 + ['group2']*3
inside_group = ['row1', 'row2', 'row3']*2
column = ['col1', 'col2']

tup = list(zip(groups, inside_group))

In [4]:
groups = ['group1']*3 + ['group2']*3
groups

['group1', 'group1', 'group1', 'group2', 'group2', 'group2']

In [5]:
inside_group = ['row1', 'row2', 'row3']*2
inside_group

['row1', 'row2', 'row3', 'row1', 'row2', 'row3']

In [6]:
column = ['col1', 'col2']
column

['col1', 'col2']

In [7]:
tup

[('group1', 'row1'),
 ('group1', 'row2'),
 ('group1', 'row3'),
 ('group2', 'row1'),
 ('group2', 'row2'),
 ('group2', 'row3')]

In [11]:
ind_tuple = list(zip(groups, inside_group))

In [14]:
index = pd.MultiIndex.from_tuples(tuples = ind_tuple)
index

MultiIndex([('group1', 'row1'),
            ('group1', 'row2'),
            ('group1', 'row3'),
            ('group2', 'row1'),
            ('group2', 'row2'),
            ('group2', 'row3')],
           )

## Multi Index

In [18]:
df = pd.DataFrame(
    data = np.random.rand(6,2),
    index=index,
    columns= column
)
df

                 col1      col2
group1 row1  0.775377  0.696202
       row2  0.273189  0.533071
       row3  0.959544  0.739802
group2 row1  0.675620  0.040558
       row2  0.909252  0.821205
       row3  0.831601  0.267382

In [20]:
df.loc

In [22]:
g1 = df.loc['group1']

In [23]:
g1.loc['row1']

col1    0.775377
col2    0.696202
Name: row1, dtype: float64

In [28]:
df.loc['group1'].loc['row1']

col1    0.775377
col2    0.696202
Name: row1, dtype: float64

In [31]:
df.index.names = ['groups', 'rows']

In [32]:
df

                 col1      col2
groups rows
group1 row1  0.775377  0.696202
       row2  0.273189  0.533071
       row3  0.959544  0.739802
group2 row1  0.675620  0.040558
       row2  0.909252  0.821205
       row3  0.831601  0.267382

## cross section methode

In [33]:
df.xs('group1')

          col1      col2
rows
row1  0.775377  0.696202
row2  0.273189  0.533071
row3  0.959544  0.739802