In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'A' : [1, 2, np.nan, 3],
    'B' : [2, np.nan, np.nan, 4],
    'C' : [7, 8, 9, 4]
}

df = pd.DataFrame(data)
df

     A    B  C
0  1.0  2.0  7
1  2.0  NaN  8
2  NaN  NaN  9
3  3.0  4.0  4

### Nan value delete

In [4]:
df.dropna()

     A    B  C
0  1.0  2.0  7
3  3.0  4.0  4