In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'A' : [1, 2, np.nan, 3],
    'B' : [2, np.nan, np.nan, 4],
    'C' : [7, 8, 9, 4]
}

df = pd.DataFrame(data)
df

     A    B  C
0  1.0  2.0  7
1  2.0  NaN  8
2  NaN  NaN  9
3  3.0  4.0  4

### Nan value delete

In [4]:
df.dropna()

     A    B  C
0  1.0  2.0  7
3  3.0  4.0  4

In [5]:
df

     A    B  C
0  1.0  2.0  7
1  2.0  NaN  8
2  NaN  NaN  9
3  3.0  4.0  4

In [6]:
df.dropna(axis = 1)

   C
0  7
1  8
2  9
3  4

In [7]:
df

     A    B  C
0  1.0  2.0  7
1  2.0  NaN  8
2  NaN  NaN  9
3  3.0  4.0  4

In [10]:
df.dropna(axis = 1, inplace=True)

In [11]:
df

   C
0  7
1  8
2  9
3  4

In [12]:
data = {
    'A' : [1, 2, np.nan, 3],
    'B' : [2, np.nan, np.nan, 4],
    'C' : [7, 8, 9, 4]
}

df = pd.DataFrame(data)
df

     A    B  C
0  1.0  2.0  7
1  2.0  NaN  8
2  NaN  NaN  9
3  3.0  4.0  4

In [13]:
df.dropna(axis = 0)

     A    B  C
0  1.0  2.0  7
3  3.0  4.0  4

## Threshold use

In [17]:
df.dropna(axis = 0, thresh=2)

     A    B  C
0  1.0  2.0  7
1  2.0  NaN  8
3  3.0  4.0  4

In [15]:
df

     A    B  C
0  1.0  2.0  7
1  2.0  NaN  8
2  NaN  NaN  9
3  3.0  4.0  4

## filling the datset in fillna using

In [19]:
df.fillna(value = 'missing')

         A        B  C
0      1.0      2.0  7
1      2.0  missing  8
2  missing  missing  9
3      3.0      4.0  4

In [20]:
df.fillna(value = df['C'].mean())

     A    B  C
0  1.0  2.0  7
1  2.0  7.0  8
2  7.0  7.0  9
3  3.0  4.0  4

In [24]:
df['A'].fillna(value = df['A'].mean(), inplace=True)

C:\Users\NAIM\AppData\Local\Temp\ipykernel_20240\2367495960.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['A'].fillna(value = df['A'].mean(), inplace=True)

In [27]:
df

     A    B  C
0  1.0  2.0  7
1  2.0  NaN  8
2  2.0  NaN  9
3  3.0  4.0  4