In [5]:
import pandas as pd
import numpy as np

df = pd.DataFrame(
    {
        'col1' : np.random.randint(1,10,size=10),
        'col2' : np.random.randint(100,500, size = 10),
        'col3' : np.random.choice(['staeve','bob', 'mike','sara'], size=10)
    }
)
df

   col1  col2    col3
0     9   433    sara
1     5   499  staeve
2     2   487  staeve
3     4   277    sara
4     9   403    sara
5     3   203    mike
6     2   379  staeve
7     2   345     bob
8     2   301     bob
9     4   260    sara

## Dataset information check.
- showing 1st 5 data

In [8]:
# sshowing the data sample
df.head(10)

   col1  col2    col3
0     9   433    sara
1     5   499  staeve
2     2   487  staeve
3     4   277    sara
4     9   403    sara
5     3   203    mike
6     2   379  staeve
7     2   345     bob
8     2   301     bob
9     4   260    sara

In [10]:
# Unic value check
df['col3'].unique()

array(['sara', 'staeve', 'mike', 'bob'], dtype=object)

In [12]:
# count uninc value
df['col3'].nunique()

4

In [13]:
# how mant times of count of the unic value
df['col3'].value_counts()

col3
sara      4
staeve    3
bob       2
mike      1
Name: count, dtype: int64

In [15]:
## check info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    10 non-null     int64
 1   col2    10 non-null     int64
 2   col3    10 non-null     object
dtypes: int64(2), object(1)
memory usage: 368.0+ bytes

In [16]:
df.sort_values(by='col2')

   col1  col2    col3
5     3   203    mike
9     4   260    sara
3     4   277    sara
8     2   301     bob
7     2   345     bob
6     2   379  staeve
4     9   403    sara
0     9   433    sara
2     2   487  staeve
1     5   499  staeve

In [17]:
df.sort_values(by='col1')

   col1  col2    col3
2     2   487  staeve
7     2   345     bob
6     2   379  staeve
8     2   301     bob
5     3   203    mike
3     4   277    sara
9     4   260    sara
1     5   499  staeve
4     9   403    sara
0     9   433    sara

In [18]:
def times3(x):
    return x*3

In [19]:
df['col2'].apply(times3)

0    1299
1    1497
2    1461
3     831
4    1209
5     609
6    1137
7    1035
8     903
9     780
Name: col2, dtype: int64

In [20]:
df['col3'].apply(len)

0    4
1    6
2    6
3    4
4    4
5    4
6    6
7    3
8    3
9    4
Name: col3, dtype: int64

In [ ]:
# comma seperated value
df.to_csv('test.csv')

In [22]:
pd.read_csv('test.csv')

   Unnamed: 0  col1  col2    col3
0           0     9   433    sara
1           1     5   499  staeve
2           2     2   487  staeve
3           3     4   277    sara
4           4     9   403    sara
5           5     3   203    mike
6           6     2   379  staeve
7           7     2   345     bob
8           8     2   301     bob
9           9     4   260    sara

In [23]:
pd.read_csv('test.csv', index_col=0)

   col1  col2    col3
0     9   433    sara
1     5   499  staeve
2     2   487  staeve
3     4   277    sara
4     9   403    sara
5     3   203    mike
6     2   379  staeve
7     2   345     bob
8     2   301     bob
9     4   260    sara