In [6]:
import numpy as np
import pandas as pd

In [7]:
left = pd.DataFrame(
    {
        'key1' : ['k0', 'k1', 'k2', 'k3'],
        'A' : np.random.randint(1,10, size = 4),
        'B' : np.random.randint(1,10, size = 4)

    }
)

right = pd.DataFrame(
    {
        'key1' : ['k0', 'k2', 'k4', 'k5'],
        'C' : np.random.randint(1,10, size = 4),
        'D' : np.random.randint(1,10, size = 4)

    }
)

In [8]:
left

  key1  A  B
0   k0  1  7
1   k1  2  8
2   k2  8  2
3   k3  3  7

In [9]:
right

  key1  C  D
0   k0  5  6
1   k2  6  4
2   k4  8  6
3   k5  9  1

In [10]:
# By default it set inner join
# pd.merge(left,right, on= 'key1')
#or
pd.merge(left, right, on= 'key1', how = 'inner')

  key1  A  B  C  D
0   k0  1  7  5  6
1   k2  8  2  6  4

In [11]:
pd.merge(left, right, on='key1', how= 'outer')

  key1    A    B    C    D
0   k0  1.0  7.0  5.0  6.0
1   k1  2.0  8.0  NaN  NaN
2   k2  8.0  2.0  6.0  4.0
3   k3  3.0  7.0  NaN  NaN
4   k4  NaN  NaN  8.0  6.0
5   k5  NaN  NaN  9.0  1.0

In [12]:
pd.merge(left, right, on= 'key1', how= 'left')

  key1  A  B    C    D
0   k0  1  7  5.0  6.0
1   k1  2  8  NaN  NaN
2   k2  8  2  6.0  4.0
3   k3  3  7  NaN  NaN

In [13]:
pd.merge(left, right, on='key1', how= 'right')

  key1    A    B  C  D
0   k0  1.0  7.0  5  6
1   k2  8.0  2.0  6  4
2   k4  NaN  NaN  8  6
3   k5  NaN  NaN  9  1

In [14]:
left = pd.DataFrame(
    {
        'A' : np.random.randint(1,10, size = 4),
        'B' : np.random.randint(1,10, size = 4)

    }, index= [0,2,3,4]
)
right = pd.DataFrame(
    {
        'A' : np.random.randint(1,10, size = 4),
        'B' : np.random.randint(1,10, size = 4)

    }, index= [0,1,2,3]
)

In [15]:
left

   A  B
0  1  8
2  3  8
3  4  9
4  9  5

In [16]:
right

   A  B
0  2  7
1  3  3
2  1  6
3  8  2

In [17]:
left.join(right, lsuffix='_left', rsuffix='_right')

   A_left  B_left  A_right  B_right
0       1       8      2.0      7.0
2       3       8      1.0      6.0
3       4       9      8.0      2.0
4       9       5      NaN      NaN

In [18]:
# left.join(right, how='inner')