In [1]:
import numpy as np
import pandas as pd

In [11]:
left = pd.DataFrame(
    {
        'key1' : ['k0', 'k1', 'k2', 'k3'],
        'A' : np.random.randint(1,10, size = 4),
        'B' : np.random.randint(1,10, size = 4)

    }
)

right = pd.DataFrame(
    {
        'key1' : ['k0', 'k2', 'k4', 'k5'],
        'C' : np.random.randint(1,10, size = 4),
        'D' : np.random.randint(1,10, size = 4)

    }
)

In [12]:
left

  key1  A  B
0   k0  1  1
1   k1  9  8
2   k2  5  6
3   k3  3  5

In [13]:
right

  key1  C  D
0   k0  7  1
1   k2  3  9
2   k4  1  4
3   k5  3  1

In [16]:
# By default it set inner join
# pd.merge(left,right, on= 'key1')
#or
pd.merge(left, right, on= 'key1', how = 'inner')

  key1  A  B  C  D
0   k0  1  1  7  1
1   k2  5  6  3  9

In [17]:
pd.merge(left, right, on='key1', how= 'outer')

  key1    A    B    C    D
0   k0  1.0  1.0  7.0  1.0
1   k1  9.0  8.0  NaN  NaN
2   k2  5.0  6.0  3.0  9.0
3   k3  3.0  5.0  NaN  NaN
4   k4  NaN  NaN  1.0  4.0
5   k5  NaN  NaN  3.0  1.0

In [19]:
pd.merge(left, right, on= 'key1', how= 'left')

  key1  A  B    C    D
0   k0  1  1  7.0  1.0
1   k1  9  8  NaN  NaN
2   k2  5  6  3.0  9.0
3   k3  3  5  NaN  NaN

In [20]:
pd.merge(left, right, on='key1', how= 'right')

  key1    A    B  C  D
0   k0  1.0  1.0  7  1
1   k2  5.0  6.0  3  9
2   k4  NaN  NaN  1  4
3   k5  NaN  NaN  3  1