In [37]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\NAIM\miniconda3\envs\mlenv\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\NAIM\miniconda3\envs\mlenv\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\NAIM\AppData\Roaming\Python\Python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\NAIM\miniconda3\envs\mlenv\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\NAIM\AppData\Roaming\Python\Python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [38]:
import numpy as np
import pandas as pd

In [39]:
data = np.arange(5,10)
data

array([5, 6, 7, 8, 9])

In [40]:
pd_series = pd.Series(data=data)
pd_series

0    5
1    6
2    7
3    8
4    9
dtype: int64

In [41]:
pd_series[0]

np.int64(5)

In [42]:
index = ['a', 'b', 'c', 'd', 'e']

In [43]:
pd_series2 = pd.Series(data = data, index=index)
pd_series2

a    5
b    6
c    7
d    8
e    9
dtype: int64

In [44]:
pd_series2['a']

np.int64(5)

In [45]:
pd_series.index

RangeIndex(start=0, stop=5, step=1)

In [46]:
pd_series2.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='str')

In [47]:
pd_series.index = index
pd_series

a    5
b    6
c    7
d    8
e    9
dtype: int64

In [48]:
data = {
    'a' : 2,
    'b' :345,
    'c' : 78
}

pd_series3 = pd.Series(data=data)
pd_series3

a      2
b    345
c     78
dtype: int64

In [49]:
data = np.random.rand(6,5)
data

array([[0.42750041, 0.07578352, 0.97478375, 0.3412112 , 0.50865594],
       [0.94909545, 0.36777008, 0.55043847, 0.33856385, 0.76898916],
       [0.47267315, 0.38869047, 0.9737604 , 0.75486275, 0.40219851],
       [0.96036501, 0.17028894, 0.39083953, 0.18469139, 0.17522583],
       [0.7495881 , 0.11153727, 0.02533868, 0.205982  , 0.91148734],
       [0.3096346 , 0.96667024, 0.35732402, 0.89407385, 0.28721161]])

In [50]:
df = pd.DataFrame(data = data)
df

          0         1         2         3         4
0  0.427500  0.075784  0.974784  0.341211  0.508656
1  0.949095  0.367770  0.550438  0.338564  0.768989
2  0.472673  0.388690  0.973760  0.754863  0.402199
3  0.960365  0.170289  0.390840  0.184691  0.175226
4  0.749588  0.111537  0.025339  0.205982  0.911487
5  0.309635  0.966670  0.357324  0.894074  0.287212

In [51]:
df[0]

0    0.427500
1    0.949095
2    0.472673
3    0.960365
4    0.749588
5    0.309635
Name: 0, dtype: float64

In [52]:
df[1]

0    0.075784
1    0.367770
2    0.388690
3    0.170289
4    0.111537
5    0.966670
Name: 1, dtype: float64

In [53]:
type(df[1])

pandas.Series

In [54]:
type(df)

pandas.DataFrame

In [56]:
df2 = pd.DataFrame(
    data = data,
    index = ['row1', 'row2','row3','row4','row5','row6'],
    columns=['col1', 'col2', 'col3', 'col4', 'col5']
)

df2

          col1      col2      col3      col4      col5
row1  0.427500  0.075784  0.974784  0.341211  0.508656
row2  0.949095  0.367770  0.550438  0.338564  0.768989
row3  0.472673  0.388690  0.973760  0.754863  0.402199
row4  0.960365  0.170289  0.390840  0.184691  0.175226
row5  0.749588  0.111537  0.025339  0.205982  0.911487
row6  0.309635  0.966670  0.357324  0.894074  0.287212

In [60]:
df2[['col4', 'col2', 'col3']]

          col4      col2      col3
row1  0.341211  0.075784  0.974784
row2  0.338564  0.367770  0.550438
row3  0.754863  0.388690  0.973760
row4  0.184691  0.170289  0.390840
row5  0.205982  0.111537  0.025339
row6  0.894074  0.966670  0.357324