In [15]:
print("Hello,World!")

Hello,World!

In [16]:
import pandas as pd
import numpy as np


data = np.random.rand(9,6)

In [17]:
df = pd.DataFrame(
    data = data,
    index = ['row1', 'row2','row3','row4','row5','row6','row7','row8','row9'],
    columns = ['col1', 'col2', 'col3', 'col4', 'col5', 'col6']
)

df

          col1      col2      col3      col4      col5      col6
row1  0.179830  0.575302  0.394519  0.504107  0.088935  0.125651
row2  0.649436  0.185927  0.763951  0.879847  0.283692  0.167360
row3  0.372118  0.470804  0.949046  0.634095  0.214048  0.054016
row4  0.967260  0.929268  0.836236  0.174101  0.694844  0.987956
row5  0.062549  0.115457  0.050642  0.811318  0.097382  0.773910
row6  0.789263  0.454667  0.352962  0.835334  0.175440  0.980248
row7  0.173043  0.425287  0.175155  0.772328  0.866511  0.528541
row8  0.897104  0.428057  0.133068  0.264802  0.524770  0.252151
row9  0.474827  0.543541  0.755797  0.832664  0.048296  0.496226

In [18]:
df < 0.5

       col1   col2   col3   col4   col5   col6
row1   True  False   True  False   True   True
row2  False   True  False  False   True   True
row3   True   True  False  False   True   True
row4  False  False  False   True  False  False
row5   True   True   True  False   True  False
row6  False   True   True  False   True  False
row7   True   True   True  False  False  False
row8  False   True   True   True  False   True
row9   True  False  False  False   True   True

In [19]:
df > 0.5

       col1   col2   col3   col4   col5   col6
row1  False   True  False   True  False  False
row2   True  False   True   True  False  False
row3  False  False   True   True  False  False
row4   True   True   True  False   True   True
row5  False  False  False   True  False   True
row6   True  False  False   True  False   True
row7  False  False  False   True   True   True
row8   True  False  False  False   True  False
row9  False   True   True   True  False  False

In [20]:
bool_df = df > 0.5

In [21]:
df[bool_df]

          col1      col2      col3      col4      col5      col6
row1       NaN  0.575302       NaN  0.504107       NaN       NaN
row2  0.649436       NaN  0.763951  0.879847       NaN       NaN
row3       NaN       NaN  0.949046  0.634095       NaN       NaN
row4  0.967260  0.929268  0.836236       NaN  0.694844  0.987956
row5       NaN       NaN       NaN  0.811318       NaN  0.773910
row6  0.789263       NaN       NaN  0.835334       NaN  0.980248
row7       NaN       NaN       NaN  0.772328  0.866511  0.528541
row8  0.897104       NaN       NaN       NaN  0.524770       NaN
row9       NaN  0.543541  0.755797  0.832664       NaN       NaN

In [22]:
df[df > 0.5]

          col1      col2      col3      col4      col5      col6
row1       NaN  0.575302       NaN  0.504107       NaN       NaN
row2  0.649436       NaN  0.763951  0.879847       NaN       NaN
row3       NaN       NaN  0.949046  0.634095       NaN       NaN
row4  0.967260  0.929268  0.836236       NaN  0.694844  0.987956
row5       NaN       NaN       NaN  0.811318       NaN  0.773910
row6  0.789263       NaN       NaN  0.835334       NaN  0.980248
row7       NaN       NaN       NaN  0.772328  0.866511  0.528541
row8  0.897104       NaN       NaN       NaN  0.524770       NaN
row9       NaN  0.543541  0.755797  0.832664       NaN       NaN

In [23]:
df['col3'] > 0.5

row1    False
row2     True
row3     True
row4     True
row5    False
row6    False
row7    False
row8    False
row9     True
Name: col3, dtype: bool

In [24]:
bool_lsr = df['col3'] > 0.5

In [25]:
df[bool_lsr]

          col1      col2      col3      col4      col5      col6
row2  0.649436  0.185927  0.763951  0.879847  0.283692  0.167360
row3  0.372118  0.470804  0.949046  0.634095  0.214048  0.054016
row4  0.967260  0.929268  0.836236  0.174101  0.694844  0.987956
row9  0.474827  0.543541  0.755797  0.832664  0.048296  0.496226

In [26]:
df[df['col3']>0.5]

          col1      col2      col3      col4      col5      col6
row2  0.649436  0.185927  0.763951  0.879847  0.283692  0.167360
row3  0.372118  0.470804  0.949046  0.634095  0.214048  0.054016
row4  0.967260  0.929268  0.836236  0.174101  0.694844  0.987956
row9  0.474827  0.543541  0.755797  0.832664  0.048296  0.496226

In [27]:
df['col3'] > 0.5 or df['col5'] < 0.5

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [28]:
boolsr = (df['col2'] > 0.5) | (df['col4'] < 0.5)

In [29]:
res = df[boolsr]

In [30]:
res[['col1', 'col2']]

          col1      col2
row1  0.179830  0.575302
row4  0.967260  0.929268
row8  0.897104  0.428057
row9  0.474827  0.543541

In [31]:
df

          col1      col2      col3      col4      col5      col6
row1  0.179830  0.575302  0.394519  0.504107  0.088935  0.125651
row2  0.649436  0.185927  0.763951  0.879847  0.283692  0.167360
row3  0.372118  0.470804  0.949046  0.634095  0.214048  0.054016
row4  0.967260  0.929268  0.836236  0.174101  0.694844  0.987956
row5  0.062549  0.115457  0.050642  0.811318  0.097382  0.773910
row6  0.789263  0.454667  0.352962  0.835334  0.175440  0.980248
row7  0.173043  0.425287  0.175155  0.772328  0.866511  0.528541
row8  0.897104  0.428057  0.133068  0.264802  0.524770  0.252151
row9  0.474827  0.543541  0.755797  0.832664  0.048296  0.496226

In [32]:
(df['col4'] > 0.4) & (df['col5'] <0.5)

row1     True
row2     True
row3     True
row4    False
row5     True
row6     True
row7    False
row8    False
row9     True
dtype: bool

In [33]:
a = (df['col1'] < 0.7) & (df["col3"] > 0.5)
a

row1    False
row2     True
row3     True
row4    False
row5    False
row6    False
row7    False
row8    False
row9     True
dtype: bool

In [34]:
df[a]

          col1      col2      col3      col4      col5      col6
row2  0.649436  0.185927  0.763951  0.879847  0.283692  0.167360
row3  0.372118  0.470804  0.949046  0.634095  0.214048  0.054016
row9  0.474827  0.543541  0.755797  0.832664  0.048296  0.496226

In [35]:
df['col1'] > 0.8

row1    False
row2    False
row3    False
row4     True
row5    False
row6    False
row7    False
row8     True
row9    False
Name: col1, dtype: bool

In [36]:
df[df['col1'] > 0.8]

          col1      col2      col3      col4      col5      col6
row4  0.967260  0.929268  0.836236  0.174101  0.694844  0.987956
row8  0.897104  0.428057  0.133068  0.264802  0.524770  0.252151

In [37]:
df

          col1      col2      col3      col4      col5      col6
row1  0.179830  0.575302  0.394519  0.504107  0.088935  0.125651
row2  0.649436  0.185927  0.763951  0.879847  0.283692  0.167360
row3  0.372118  0.470804  0.949046  0.634095  0.214048  0.054016
row4  0.967260  0.929268  0.836236  0.174101  0.694844  0.987956
row5  0.062549  0.115457  0.050642  0.811318  0.097382  0.773910
row6  0.789263  0.454667  0.352962  0.835334  0.175440  0.980248
row7  0.173043  0.425287  0.175155  0.772328  0.866511  0.528541
row8  0.897104  0.428057  0.133068  0.264802  0.524770  0.252151
row9  0.474827  0.543541  0.755797  0.832664  0.048296  0.496226

In [46]:
df['col5']

row1    0.088935
row2    0.283692
row3    0.214048
row4    0.694844
row5    0.097382
row6    0.175440
row7    0.866511
row8    0.524770
row9    0.048296
Name: col5, dtype: float64

In [52]:
df['col5'] == df['col2']

row1    False
row2    False
row3    False
row4    False
row5    False
row6    False
row7    False
row8    False
row9    False
dtype: bool