In [2]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\NAIM\miniconda3\envs\mlenv\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\NAIM\miniconda3\envs\mlenv\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\NAIM\AppData\Roaming\Python\Python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\NAIM\miniconda3\envs\mlenv\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\NAIM\AppData\Roaming\Python\Python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import numpy as np
import pandas as pd

In [4]:
data = np.arange(5,10)
data

array([5, 6, 7, 8, 9])

In [5]:
pd_series = pd.Series(data=data)
pd_series

0    5
1    6
2    7
3    8
4    9
dtype: int64

In [6]:
pd_series[0]

np.int64(5)

In [7]:
index = ['a', 'b', 'c', 'd', 'e']

In [8]:
pd_series2 = pd.Series(data = data, index=index)
pd_series2

a    5
b    6
c    7
d    8
e    9
dtype: int64

In [9]:
pd_series2['a']

np.int64(5)

In [10]:
pd_series.index

RangeIndex(start=0, stop=5, step=1)

In [11]:
pd_series2.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='str')

In [12]:
pd_series.index = index
pd_series

a    5
b    6
c    7
d    8
e    9
dtype: int64

In [13]:
data = {
    'a' : 2,
    'b' :345,
    'c' : 78
}

pd_series3 = pd.Series(data=data)
pd_series3

a      2
b    345
c     78
dtype: int64

In [14]:
data = np.random.rand(6,5)
data

array([[0.39764045, 0.18441761, 0.57637064, 0.16542518, 0.3643119 ],
       [0.31773112, 0.0958283 , 0.97338126, 0.80417442, 0.89748708],
       [0.62977118, 0.40925736, 0.00511563, 0.7792933 , 0.52196663],
       [0.16055212, 0.04212001, 0.84208375, 0.47887225, 0.80252554],
       [0.37332694, 0.31818554, 0.86566646, 0.69934161, 0.66868782],
       [0.4685097 , 0.18517498, 0.93405759, 0.36680431, 0.02189106]])

In [15]:
df = pd.DataFrame(data = data)
df

          0         1         2         3         4
0  0.397640  0.184418  0.576371  0.165425  0.364312
1  0.317731  0.095828  0.973381  0.804174  0.897487
2  0.629771  0.409257  0.005116  0.779293  0.521967
3  0.160552  0.042120  0.842084  0.478872  0.802526
4  0.373327  0.318186  0.865666  0.699342  0.668688
5  0.468510  0.185175  0.934058  0.366804  0.021891

In [16]:
df[0]

0    0.397640
1    0.317731
2    0.629771
3    0.160552
4    0.373327
5    0.468510
Name: 0, dtype: float64

In [17]:
df[1]

0    0.184418
1    0.095828
2    0.409257
3    0.042120
4    0.318186
5    0.185175
Name: 1, dtype: float64

In [18]:
type(df[1])

pandas.Series

In [19]:
type(df)

pandas.DataFrame

In [20]:
df2 = pd.DataFrame(
    data = data,
    index = ['row1', 'row2','row3','row4','row5','row6'],
    columns=['col1', 'col2', 'col3', 'col4', 'col5']
)

df2

          col1      col2      col3      col4      col5
row1  0.397640  0.184418  0.576371  0.165425  0.364312
row2  0.317731  0.095828  0.973381  0.804174  0.897487
row3  0.629771  0.409257  0.005116  0.779293  0.521967
row4  0.160552  0.042120  0.842084  0.478872  0.802526
row5  0.373327  0.318186  0.865666  0.699342  0.668688
row6  0.468510  0.185175  0.934058  0.366804  0.021891

In [21]:
df2[['col4', 'col2', 'col3']]

          col4      col2      col3
row1  0.165425  0.184418  0.576371
row2  0.804174  0.095828  0.973381
row3  0.779293  0.409257  0.005116
row4  0.478872  0.042120  0.842084
row5  0.699342  0.318186  0.865666
row6  0.366804  0.185175  0.934058

In [22]:
df2['new'] = np.random.rand(6)
df2

          col1      col2      col3      col4      col5       new
row1  0.397640  0.184418  0.576371  0.165425  0.364312  0.008975
row2  0.317731  0.095828  0.973381  0.804174  0.897487  0.364012
row3  0.629771  0.409257  0.005116  0.779293  0.521967  0.115316
row4  0.160552  0.042120  0.842084  0.478872  0.802526  0.924276
row5  0.373327  0.318186  0.865666  0.699342  0.668688  0.452393
row6  0.468510  0.185175  0.934058  0.366804  0.021891  0.693292

In [23]:
df2.drop(columns='new', inplace=True)
df2

          col1      col2      col3      col4      col5
row1  0.397640  0.184418  0.576371  0.165425  0.364312
row2  0.317731  0.095828  0.973381  0.804174  0.897487
row3  0.629771  0.409257  0.005116  0.779293  0.521967
row4  0.160552  0.042120  0.842084  0.478872  0.802526
row5  0.373327  0.318186  0.865666  0.699342  0.668688
row6  0.468510  0.185175  0.934058  0.366804  0.021891

In [ ]:
df2.shape

(6, 5)

In [25]:
df2

          col1      col2      col3      col4      col5
row1  0.397640  0.184418  0.576371  0.165425  0.364312
row2  0.317731  0.095828  0.973381  0.804174  0.897487
row3  0.629771  0.409257  0.005116  0.779293  0.521967
row4  0.160552  0.042120  0.842084  0.478872  0.802526
row5  0.373327  0.318186  0.865666  0.699342  0.668688
row6  0.468510  0.185175  0.934058  0.366804  0.021891

In [ ]:
df2.shape

(6, 5)

In [27]:
df2.loc['row1', 'col2']

np.float64(0.18441761475611196)

In [28]:
df2.loc[['row1','row2']]

          col1      col2      col3      col4      col5
row1  0.397640  0.184418  0.576371  0.165425  0.364312
row2  0.317731  0.095828  0.973381  0.804174  0.897487

In [30]:
df2.loc[['row1','row2'],['col4', 'col5']]

          col4      col5
row1  0.165425  0.364312
row2  0.804174  0.897487

In [31]:
df.iloc[0,1]

np.float64(0.18441761475611196)

In [32]:
df.iloc[[0,1],[2,4]]

          2         4
0  0.576371  0.364312
1  0.973381  0.897487