In [84]:
print("Hello,World!")

Hello,World!

In [85]:
import pandas as pd
import numpy as np


data = np.random.rand(9,6)

In [86]:
df = pd.DataFrame(
    data = data,
    index = ['row1', 'row2','row3','row4','row5','row6','row7','row8','row9'],
    columns = ['col1', 'col2', 'col3', 'col4', 'col5', 'col6']
)

df

          col1      col2      col3      col4      col5      col6
row1  0.517402  0.578007  0.182109  0.195579  0.581799  0.316343
row2  0.737942  0.863057  0.449736  0.854212  0.970129  0.847066
row3  0.792918  0.546876  0.113252  0.475942  0.977253  0.131442
row4  0.589098  0.194009  0.515535  0.935092  0.393258  0.635807
row5  0.311438  0.972334  0.403003  0.997845  0.854332  0.213548
row6  0.742956  0.444978  0.661003  0.540280  0.349643  0.479912
row7  0.499656  0.872350  0.184497  0.835766  0.670138  0.203014
row8  0.619018  0.521680  0.734105  0.671626  0.856898  0.284642
row9  0.559003  0.875741  0.808785  0.935812  0.046653  0.470133

In [97]:
df < 0.5

       col1   col2   col3   col4   col5   col6
row1  False  False   True   True  False   True
row2  False  False   True  False  False  False
row3  False  False   True   True  False   True
row4  False   True  False  False   True  False
row5   True  False   True  False  False   True
row6  False   True  False  False   True   True
row7   True  False   True  False  False   True
row8  False  False  False  False  False   True
row9  False  False  False  False   True   True

In [99]:
df > 0.5

       col1   col2   col3   col4   col5   col6
row1   True   True  False  False   True  False
row2   True   True  False   True   True   True
row3   True   True  False  False   True  False
row4   True  False   True   True  False   True
row5  False   True  False   True   True  False
row6   True  False   True   True  False  False
row7  False   True  False   True   True  False
row8   True   True   True   True   True  False
row9   True   True   True   True  False  False

In [100]:
bool_df = df > 0.5

In [101]:
df[bool_df]

          col1      col2      col3      col4      col5      col6
row1  0.517402  0.578007       NaN       NaN  0.581799       NaN
row2  0.737942  0.863057       NaN  0.854212  0.970129  0.847066
row3  0.792918  0.546876       NaN       NaN  0.977253       NaN
row4  0.589098       NaN  0.515535  0.935092       NaN  0.635807
row5       NaN  0.972334       NaN  0.997845  0.854332       NaN
row6  0.742956       NaN  0.661003  0.540280       NaN       NaN
row7       NaN  0.872350       NaN  0.835766  0.670138       NaN
row8  0.619018  0.521680  0.734105  0.671626  0.856898       NaN
row9  0.559003  0.875741  0.808785  0.935812       NaN       NaN

In [102]:
df[df > 0.5]

          col1      col2      col3      col4      col5      col6
row1  0.517402  0.578007       NaN       NaN  0.581799       NaN
row2  0.737942  0.863057       NaN  0.854212  0.970129  0.847066
row3  0.792918  0.546876       NaN       NaN  0.977253       NaN
row4  0.589098       NaN  0.515535  0.935092       NaN  0.635807
row5       NaN  0.972334       NaN  0.997845  0.854332       NaN
row6  0.742956       NaN  0.661003  0.540280       NaN       NaN
row7       NaN  0.872350       NaN  0.835766  0.670138       NaN
row8  0.619018  0.521680  0.734105  0.671626  0.856898       NaN
row9  0.559003  0.875741  0.808785  0.935812       NaN       NaN

In [103]:
df['col3'] > 0.5

row1    False
row2    False
row3    False
row4     True
row5    False
row6     True
row7    False
row8     True
row9     True
Name: col3, dtype: bool

In [104]:
bool_lsr = df['col3'] > 0.5

In [105]:
df[bool_lsr]

          col1      col2      col3      col4      col5      col6
row4  0.589098  0.194009  0.515535  0.935092  0.393258  0.635807
row6  0.742956  0.444978  0.661003  0.540280  0.349643  0.479912
row8  0.619018  0.521680  0.734105  0.671626  0.856898  0.284642
row9  0.559003  0.875741  0.808785  0.935812  0.046653  0.470133

In [106]:
df[df['col3']>0.5]

          col1      col2      col3      col4      col5      col6
row4  0.589098  0.194009  0.515535  0.935092  0.393258  0.635807
row6  0.742956  0.444978  0.661003  0.540280  0.349643  0.479912
row8  0.619018  0.521680  0.734105  0.671626  0.856898  0.284642
row9  0.559003  0.875741  0.808785  0.935812  0.046653  0.470133

In [107]:
df['col3'] > 0.5 or df['col5'] < 0.5

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [108]:
boolsr = (df['col2'] > 0.5) | (df['col4'] < 0.5)

In [109]:
res = df[boolsr]

In [110]:
res[['col1', 'col2']]

          col1      col2
row1  0.517402  0.578007
row2  0.737942  0.863057
row3  0.792918  0.546876
row5  0.311438  0.972334
row7  0.499656  0.872350
row8  0.619018  0.521680
row9  0.559003  0.875741

In [111]:
df

          col1      col2      col3      col4      col5      col6
row1  0.517402  0.578007  0.182109  0.195579  0.581799  0.316343
row2  0.737942  0.863057  0.449736  0.854212  0.970129  0.847066
row3  0.792918  0.546876  0.113252  0.475942  0.977253  0.131442
row4  0.589098  0.194009  0.515535  0.935092  0.393258  0.635807
row5  0.311438  0.972334  0.403003  0.997845  0.854332  0.213548
row6  0.742956  0.444978  0.661003  0.540280  0.349643  0.479912
row7  0.499656  0.872350  0.184497  0.835766  0.670138  0.203014
row8  0.619018  0.521680  0.734105  0.671626  0.856898  0.284642
row9  0.559003  0.875741  0.808785  0.935812  0.046653  0.470133

In [112]:
(df['col4'] > 0.4) & (df['col5'] <0.5)

row1    False
row2    False
row3    False
row4     True
row5    False
row6     True
row7    False
row8    False
row9     True
dtype: bool

In [114]:
a = (df['col1'] < 0.7) & (df["col3"] > 0.5)
a

row1    False
row2    False
row3    False
row4     True
row5    False
row6    False
row7    False
row8     True
row9     True
dtype: bool

In [115]:
df[a]

          col1      col2      col3      col4      col5      col6
row4  0.589098  0.194009  0.515535  0.935092  0.393258  0.635807
row8  0.619018  0.521680  0.734105  0.671626  0.856898  0.284642
row9  0.559003  0.875741  0.808785  0.935812  0.046653  0.470133

In [116]:
df['col1'] > 0.8

row1    False
row2    False
row3    False
row4    False
row5    False
row6    False
row7    False
row8    False
row9    False
Name: col1, dtype: bool

In [117]:
df[df['col1'] > 0.8]

Empty DataFrame
Columns: [col1, col2, col3, col4, col5, col6]
Index: []