In [1]:
pip install pandas

Requirement already satisfied: pandas in /home/md-naim/miniconda3/envs/ML/lib/python3.10/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in /home/md-naim/miniconda3/envs/ML/lib/python3.10/site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/md-naim/miniconda3/envs/ML/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/md-naim/miniconda3/envs/ML/lib/python3.10/site-packages (from pandas) (2026.3.post1)
Requirement already satisfied: tzdata>=2022.7 in /home/md-naim/miniconda3/envs/ML/lib/python3.10/site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /home/md-naim/miniconda3/envs/ML/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np
import pandas as pd

In [3]:
data = np.arange(5,10)
data

array([5, 6, 7, 8, 9])

In [4]:
pd_series = pd.Series(data=data)
pd_series

0    5
1    6
2    7
3    8
4    9
dtype: int64

In [5]:
pd_series[0]

np.int64(5)

In [6]:
index = ['a', 'b', 'c', 'd', 'e']

In [7]:
pd_series2 = pd.Series(data = data, index=index)
pd_series2

a    5
b    6
c    7
d    8
e    9
dtype: int64

In [8]:
pd_series2['a']

np.int64(5)

In [9]:
pd_series.index

RangeIndex(start=0, stop=5, step=1)

In [10]:
pd_series2.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [11]:
pd_series.index = index
pd_series

a    5
b    6
c    7
d    8
e    9
dtype: int64

In [12]:
data = {
    'a' : 2,
    'b' :345,
    'c' : 78
}

pd_series3 = pd.Series(data=data)
pd_series3

a      2
b    345
c     78
dtype: int64

In [13]:
data = np.random.rand(6,5)
data

array([[0.21481714, 0.76912739, 0.41889021, 0.65471115, 0.92550975],
       [0.40786593, 0.07969057, 0.85001006, 0.93978055, 0.25774406],
       [0.65129594, 0.9135683 , 0.14602096, 0.1898046 , 0.84565997],
       [0.65139567, 0.17607018, 0.95073452, 0.84294135, 0.30672615],
       [0.03454052, 0.48871672, 0.54866748, 0.02842643, 0.04240516],
       [0.67864128, 0.49680908, 0.55863927, 0.71792329, 0.72137926]])

In [14]:
df = pd.DataFrame(data = data)
df

          0         1         2         3         4
0  0.214817  0.769127  0.418890  0.654711  0.925510
1  0.407866  0.079691  0.850010  0.939781  0.257744
2  0.651296  0.913568  0.146021  0.189805  0.845660
3  0.651396  0.176070  0.950735  0.842941  0.306726
4  0.034541  0.488717  0.548667  0.028426  0.042405
5  0.678641  0.496809  0.558639  0.717923  0.721379

In [15]:
df[0]

0    0.214817
1    0.407866
2    0.651296
3    0.651396
4    0.034541
5    0.678641
Name: 0, dtype: float64

In [16]:
df[1]

0    0.769127
1    0.079691
2    0.913568
3    0.176070
4    0.488717
5    0.496809
Name: 1, dtype: float64

In [17]:
type(df[1])

pandas.core.series.Series

In [18]:
type(df)

pandas.core.frame.DataFrame

In [19]:
df2 = pd.DataFrame(
    data = data,
    index = ['row1', 'row2','row3','row4','row5','row6'],
    columns=['col1', 'col2', 'col3', 'col4', 'col5']
)

df2

          col1      col2      col3      col4      col5
row1  0.214817  0.769127  0.418890  0.654711  0.925510
row2  0.407866  0.079691  0.850010  0.939781  0.257744
row3  0.651296  0.913568  0.146021  0.189805  0.845660
row4  0.651396  0.176070  0.950735  0.842941  0.306726
row5  0.034541  0.488717  0.548667  0.028426  0.042405
row6  0.678641  0.496809  0.558639  0.717923  0.721379

In [20]:
df2[['col4', 'col2', 'col3']]

          col4      col2      col3
row1  0.654711  0.769127  0.418890
row2  0.939781  0.079691  0.850010
row3  0.189805  0.913568  0.146021
row4  0.842941  0.176070  0.950735
row5  0.028426  0.488717  0.548667
row6  0.717923  0.496809  0.558639

In [21]:
df2['new'] = np.random.rand(6)
df2

          col1      col2      col3      col4      col5       new
row1  0.214817  0.769127  0.418890  0.654711  0.925510  0.230510
row2  0.407866  0.079691  0.850010  0.939781  0.257744  0.045802
row3  0.651296  0.913568  0.146021  0.189805  0.845660  0.934496
row4  0.651396  0.176070  0.950735  0.842941  0.306726  0.423898
row5  0.034541  0.488717  0.548667  0.028426  0.042405  0.599318
row6  0.678641  0.496809  0.558639  0.717923  0.721379  0.863313

In [22]:
df2.drop(columns='new', inplace=True)
df2

          col1      col2      col3      col4      col5
row1  0.214817  0.769127  0.418890  0.654711  0.925510
row2  0.407866  0.079691  0.850010  0.939781  0.257744
row3  0.651296  0.913568  0.146021  0.189805  0.845660
row4  0.651396  0.176070  0.950735  0.842941  0.306726
row5  0.034541  0.488717  0.548667  0.028426  0.042405
row6  0.678641  0.496809  0.558639  0.717923  0.721379

In [23]:
df2.shape

(6, 5)

In [24]:
df2

          col1      col2      col3      col4      col5
row1  0.214817  0.769127  0.418890  0.654711  0.925510
row2  0.407866  0.079691  0.850010  0.939781  0.257744
row3  0.651296  0.913568  0.146021  0.189805  0.845660
row4  0.651396  0.176070  0.950735  0.842941  0.306726
row5  0.034541  0.488717  0.548667  0.028426  0.042405
row6  0.678641  0.496809  0.558639  0.717923  0.721379

In [25]:
df2.shape

(6, 5)

In [26]:
df2.loc['row1', 'col2']

np.float64(0.7691273899177071)

In [27]:
df2.loc[['row1','row2']]

          col1      col2     col3      col4      col5
row1  0.214817  0.769127  0.41889  0.654711  0.925510
row2  0.407866  0.079691  0.85001  0.939781  0.257744

In [28]:
df2.loc[['row1','row2'],['col4', 'col5']]

          col4      col5
row1  0.654711  0.925510
row2  0.939781  0.257744

In [29]:
df.iloc[0,1]

np.float64(0.7691273899177071)

In [30]:
df.iloc[[0,1],[2,4]]

         2         4
0  0.41889  0.925510
1  0.85001  0.257744

In [31]:
df.shape

(6, 5)

In [32]:
df.abs

<bound method NDFrame.abs of           0         1         2         3         4
0  0.214817  0.769127  0.418890  0.654711  0.925510
1  0.407866  0.079691  0.850010  0.939781  0.257744
2  0.651296  0.913568  0.146021  0.189805  0.845660
3  0.651396  0.176070  0.950735  0.842941  0.306726
4  0.034541  0.488717  0.548667  0.028426  0.042405
5  0.678641  0.496809  0.558639  0.717923  0.721379>

In [34]:
df.sub

<bound method DataFrame.sub of           0         1         2         3         4
0  0.214817  0.769127  0.418890  0.654711  0.925510
1  0.407866  0.079691  0.850010  0.939781  0.257744
2  0.651296  0.913568  0.146021  0.189805  0.845660
3  0.651396  0.176070  0.950735  0.842941  0.306726
4  0.034541  0.488717  0.548667  0.028426  0.042405
5  0.678641  0.496809  0.558639  0.717923  0.721379>

In [35]:
df.head

<bound method NDFrame.head of           0         1         2         3         4
0  0.214817  0.769127  0.418890  0.654711  0.925510
1  0.407866  0.079691  0.850010  0.939781  0.257744
2  0.651296  0.913568  0.146021  0.189805  0.845660
3  0.651396  0.176070  0.950735  0.842941  0.306726
4  0.034541  0.488717  0.548667  0.028426  0.042405
5  0.678641  0.496809  0.558639  0.717923  0.721379>

In [36]:
df.map

<bound method DataFrame.map of           0         1         2         3         4
0  0.214817  0.769127  0.418890  0.654711  0.925510
1  0.407866  0.079691  0.850010  0.939781  0.257744
2  0.651296  0.913568  0.146021  0.189805  0.845660
3  0.651396  0.176070  0.950735  0.842941  0.306726
4  0.034541  0.488717  0.548667  0.028426  0.042405
5  0.678641  0.496809  0.558639  0.717923  0.721379>

In [37]:
df.sample

<bound method NDFrame.sample of           0         1         2         3         4
0  0.214817  0.769127  0.418890  0.654711  0.925510
1  0.407866  0.079691  0.850010  0.939781  0.257744
2  0.651296  0.913568  0.146021  0.189805  0.845660
3  0.651396  0.176070  0.950735  0.842941  0.306726
4  0.034541  0.488717  0.548667  0.028426  0.042405
5  0.678641  0.496809  0.558639  0.717923  0.721379>

In [38]:
df.add

<bound method DataFrame.add of           0         1         2         3         4
0  0.214817  0.769127  0.418890  0.654711  0.925510
1  0.407866  0.079691  0.850010  0.939781  0.257744
2  0.651296  0.913568  0.146021  0.189805  0.845660
3  0.651396  0.176070  0.950735  0.842941  0.306726
4  0.034541  0.488717  0.548667  0.028426  0.042405
5  0.678641  0.496809  0.558639  0.717923  0.721379>

In [39]:
df.add_prefix

<bound method NDFrame.add_prefix of           0         1         2         3         4
0  0.214817  0.769127  0.418890  0.654711  0.925510
1  0.407866  0.079691  0.850010  0.939781  0.257744
2  0.651296  0.913568  0.146021  0.189805  0.845660
3  0.651396  0.176070  0.950735  0.842941  0.306726
4  0.034541  0.488717  0.548667  0.028426  0.042405
5  0.678641  0.496809  0.558639  0.717923  0.721379>

In [40]:
df.add_suffix

<bound method NDFrame.add_suffix of           0         1         2         3         4
0  0.214817  0.769127  0.418890  0.654711  0.925510
1  0.407866  0.079691  0.850010  0.939781  0.257744
2  0.651296  0.913568  0.146021  0.189805  0.845660
3  0.651396  0.176070  0.950735  0.842941  0.306726
4  0.034541  0.488717  0.548667  0.028426  0.042405
5  0.678641  0.496809  0.558639  0.717923  0.721379>

In [41]:
df.all

<bound method DataFrame.all of           0         1         2         3         4
0  0.214817  0.769127  0.418890  0.654711  0.925510
1  0.407866  0.079691  0.850010  0.939781  0.257744
2  0.651296  0.913568  0.146021  0.189805  0.845660
3  0.651396  0.176070  0.950735  0.842941  0.306726
4  0.034541  0.488717  0.548667  0.028426  0.042405
5  0.678641  0.496809  0.558639  0.717923  0.721379>